import CoreData

struct JobOffersEntities {
  static let mock = [
    JobOfferEntity(
      companyName: "AV Studio",
      jobTitle: "UX Designér/ka",
      offerUrl: "https://www.startupjobs.cz/nabidka/69109/ux-designer-ka",
      salary: "40 000kč",
      notes: "Toto je poznámka",
      dateOfSentCv: DateComponents(year: 2024, month: 4, day: 12).date ?? Date(),
      response: false,
      dateOfResponse: nil,
      firstRoundOfInterview: false,
      dateOfFirstRoundOfInterview: nil,
      secondRoundOfInterview: false,
      dateOfSecondRoundOfInterview: nil,
      thirdRoundOfInterview: false,
      dateOfThirdRoundOfInterview: nil,
      fullTextOffer: "Celý text inzerátu",
      status: "No response", 
      jobLocation: "Praha", 
      jobLevel: "medior", 
      typesOfEmployment: "Part-time", 
      workingArrangements: nil),
    JobOfferEntity(
      companyName: "Futured",
      jobTitle: "Full-stack vývojář",
      offerUrl: "https://www.startupjobs.cz/nabidka/69531/full-stack-vyvojar-javascript-typescript",
      salary: "",
      notes: "",
      dateOfSentCv: DateComponents(year: 2024, month: 4, day: 1).date ?? Date(),
      response: true,
      dateOfResponse: DateComponents(year: 2024, month: 4, day: 10).date ?? Date(),
      firstRoundOfInterview: true,
      dateOfFirstRoundOfInterview: DateComponents(year: 2024, month: 4, day: 16).date ?? Date(),
      secondRoundOfInterview: false,
      dateOfSecondRoundOfInterview: nil,
      thirdRoundOfInterview: false,
      dateOfThirdRoundOfInterview: nil,
      fullTextOffer: nil,
      status: "Interview", 
      jobLocation: "Brno", 
      jobLevel: "senior", 
      typesOfEmployment: "Full-time", 
      workingArrangements: "on-site"),
    JobOfferEntity(
      companyName: "Apple",
      jobTitle: "iOS Developer",
      offerUrl: "",
      salary: "",
      notes: "",
      dateOfSentCv: DateComponents(year: 2024, month: 4, day: 5).date ?? Date(),
      response: true,
      dateOfResponse: DateComponents(year: 2024, month: 4, day: 8).date ?? Date(),
      firstRoundOfInterview: true,
      dateOfFirstRoundOfInterview: DateComponents(year: 2024, month: 4, day: 10).date ?? Date(),
      secondRoundOfInterview: false,
      dateOfSecondRoundOfInterview: nil,
      thirdRoundOfInterview: false,
      dateOfThirdRoundOfInterview: nil,
      fullTextOffer: nil,
      status: "Accepted", 
      jobLocation: nil, 
      jobLevel: "junior",
      typesOfEmployment: nil, 
      workingArrangements: "hybrid"),
    JobOfferEntity(
      companyName: "Google",
      jobTitle: "UX Designer",
      offerUrl: "",
      salary: "50 000 CZK",
      notes: "",
      dateOfSentCv: DateComponents(year: 2024, month: 4, day: 4).date ?? Date(),
      response: true,
      dateOfResponse: DateComponents(year: 2024, month: 4, day: 11).date ?? Date(),
      firstRoundOfInterview: false,
      dateOfFirstRoundOfInterview: nil,
      secondRoundOfInterview: false,
      dateOfSecondRoundOfInterview: nil,
      thirdRoundOfInterview: false,
      dateOfThirdRoundOfInterview: nil,
      fullTextOffer: nil,
      status: "Rejected", 
      jobLocation: "Ostrava",
      jobLevel: nil, 
      typesOfEmployment: "Full-time", 
      workingArrangements: "remote")
  ]
}
